#pragma once

#define NTF_ENABLE 1
#define NTF_DISABLE 0

#ifndef SHOGLE_USE_CUSTOM_ASSERT
#define SHOGLE_USE_CUSTOM_ASSERT NTF_ENABLE
#endif

#ifndef SHOGLE_ENABLE_INTERNAL_LOGS
#define SHOGLE_ENABLE_INTERNAL_LOGS NTF_ENABLE
#endif

// Library things
#ifndef SHOGLE_USE_GLM // Might replace glm at some point (?)
#define SHOGLE_USE_GLM NTF_ENABLE
#endif

#ifndef SHOGLE_USE_GLFW
#define SHOGLE_USE_GLFW NTF_ENABLE
#endif

#ifndef SHOGLE_ENABLE_IMGUI
#define SHOGLE_ENABLE_IMGUI NTF_DISABLE
#endif

// STL things
#ifndef SHOGLE_USE_STL_OPTIONAL
#define SHOGLE_USE_STL_OPTIONAL NTF_ENABLE
#endif

#ifndef SHOGLE_USE_STL_COMPLEX
#define SHOGLE_USE_STL_COMPLEX NTF_ENABLE
#endif

// Asset things
#ifndef SHOGLE_ASSIMP_WEIGHTS
#define SHOGLE_ASSIMP_WEIGHTS 4
#endif
