if (SHOGLE_DISABLE_INERNAL_LOGS)
  list(APPEND SHOGLE_DEFINITIONS SHOGLE_DISABLE_INERNAL_LOGS=1)
endif()

if (SHOGLE_ENABLE_IMGUI)
  list(APPEND SHOGLE_DEFINITIONS SHOGLE_ENABLE_IMGUI=1)
endif()

if (SHOGLE_ENABLE_GLFW)
  list(APPEND SHOGLE_DEFINITIONS SHOGLE_ENABLE_GLFW=1)
endif()
