if (SHOGLE_ENABLE_INTERNAL_LOGS)
  list(APPEND SHOGLE_ENABLE_INTERNAL_LOGS=1)
endif()

if (SHOGLE_ENABLE_IMGUI)
  list(APPEND SHOGLE_DEFS SHOGLE_ENABLE_IMGUI=1)
endif()

if (SHOGLE_ENABLE_GLFW)
  list(APPEND SHOGLE_DEFS SHOGLE_ENABLE_GLFW=1)
endif()
